---
abstract: 'Lexically disable autovivification.'
author:
  - 'Vincent Pit <perl@profvince.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
  XSLoader: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: autovivification
no_index:
  directory:
    - t
    - inc
requires:
  XSLoader: 0
  perl: 5.008003
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=autovivification
  homepage: http://search.cpan.org/dist/autovivification/
  license: http://dev.perl.org/licenses/
  repository: http://git.profvince.com/?p=perl%2Fmodules%2Fautovivification.git
version: 0.10
